
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jtjlxhyythzegigsrqnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0amx4aHl5dGh6ZWdpZ3NycW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2OTUwNzQsImV4cCI6MjA1NDI3MTA3NH0.fL_4jJdOI_E3xNJK1YXk3DIKIzAlY01sKMUm19KPPEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
